name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -race -cover ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: .
          args: ./...
